CREATE TABLE SERVICE_MESSAGE (
  ID          VARCHAR(40),
  TIMESTAMP   BIGINT,
  APPLICATION VARCHAR(50),
  HOSTNAME    VARCHAR(45),
  LEVEL       INTEGER,
  PAYLOAD     VARCHAR(400),
  PRIMARY KEY (ID)
);